; Landmarks indexes (see data/maps/landmarks.asm)
	const_def
	const LANDMARK_SPECIAL           ; 00
; Johto landmarks
	const LANDMARK_TWINLEAF_TOWN
	const LANDMARK_ROUTE_201
	const LANDMARK_VERITY_LAKEFRONT
	const LANDMARK_LAKE_VERITY
	const LANDMARK_SANDGEM_TOWN
	const LANDMARK_ROUTE_202
	const LANDMARK_JUBILIFE_CITY
	const LANDMARK_ROUTE_203
	const LANDMARK_OREBURGH_GATE
	const LANDMARK_OREBURGH_CITY
	const LANDMARK_OREBURGH_MINE
	const LANDMARK_ROUTE_204
	const LANDMARK_RAVAGED_PATH
	const LANDMARK_FLOAROMA_TOWN
	const LANDMARK_VALLEY_WINDWORKS
	const LANDMARK_ROUTE_205_SOUTH
	const LANDMARK_FLOAROMA_MEADOW
	const LANDMARK_FUEGO_IRONWORKS
	const LANDMARK_ETERNA_FOREST
	const LANDMARK_OLD_CHATEAU
	const LANDMARK_ROUTE_205_NORTH
	const LANDMARK_ETERNA_CITY
	const LANDMARK_ROUTE_211
	const LANDMARK_ROUTE_206
	const LANDMARK_WAYWARD_CAVE
	const LANDMARK_ROUTE_207
	const LANDMARK_MT_CORONET
	const LANDMARK_ROUTE_208
	const LANDMARK_HEARTHOME_CITY
	const LANDMARK_AMITY_SQUARE
	const LANDMARK_ROUTE_209
	const LANDMARK_SOLACEON_TOWN
	const LANDMARK_SOLACEON_RUINS
	const LANDMARK_ROUTE_210
	const LANDMARK_ROUTE_215
	const LANDMARK_VEILSTONE_CITY
	const LANDMARK_ROUTE_214
	const LANDMARK_MANIAC_TUNNEL
	const LANDMARK_LAKE_VALOR
	const LANDMARK_ROUTE_213
	const LANDMARK_PASTORIA_CITY
	const LANDMARK_GREAT_MARSH
	const LANDMARK_ROUTE_212
	const LANDMARK_POKEMON_MANSION
	const LANDMARK_ROUTE_218
	const LANDMARK_CANALAVE_CITY
	const LANDMARK_IRON_ISLAND
	const LANDMARK_ROUTE_216
	const LANDMARK_ROUTE_217
	const LANDMARK_LAKE_ACUITY
	const LANDMARK_SNOWPOINT_CITY
	const LANDMARK_SNOWPOINT_TEMPLE
	const LANDMARK_SPEAR_PILLAR
	const LANDMARK_ROUTE_222
	const LANDMARK_SUNYSHORE_CITY
	const LANDMARK_ROUTE_223
	const LANDMARK_VICTORY_ROAD
	const LANDMARK_POKEMON_LEAGUE
	const LANDMARK_ROUTE_219
	const LANDMARK_ROUTE_220
	const LANDMARK_ROUTE_221
	const LANDMARK_PAL_PARK
	const LANDMARK_ROUTE_224
	const LANDMARK_FIGHT_AREA
	const LANDMARK_BATTLE_FRONTIER
	const LANDMARK_ROUTE_225
	const LANDMARK_SURVIVAL_AREA
	const LANDMARK_ROUTE_226
	const LANDMARK_ROUTE_227
	const LANDMARK_STARK_MOUNTAIN
	const LANDMARK_ROUTE_228
	const LANDMARK_ROUTE_229
	const LANDMARK_RESORT_AREA
	const LANDMARK_ROUTE_230
	const LANDMARK_FULLMOON_ISLAND
	const LANDMARK_NEWMOON_ISLAND
	const LANDMARK_SEABREAK_PATH
	const LANDMARK_FLOWER_PARADISE
DEF NUM_LANDMARKS EQU const_value

; used in CaughtData
	const_def $7f, -1
	const LANDMARK_EVENT             ; $7f
	const LANDMARK_GIFT              ; $7e

; Regions
	const_def
	const JOHTO_REGION ; 0
	const KANTO_REGION ; 1
DEF NUM_REGIONS EQU const_value
