; song ids
; Music indexes (see audio/music_pointers.asm)
	const_def
	const MUSIC_NONE                         ; 00
	const MUSIC_TITLE                        ; 01
	const MUSIC_ROUTE_1                      ; 02
	const MUSIC_ROUTE_3                      ; 03
	const MUSIC_ROUTE_12                     ; 04
	const MUSIC_SPECIAL_PROGRAM              ; 05
	const MUSIC_POKEMON_CENTER               ; 09
	const MUSIC_HIKER_ENCOUNTER              ; 0a
	const MUSIC_LASS_ENCOUNTER               ; 0b
	const MUSIC_OFFICER_ENCOUNTER            ; 0c
	const MUSIC_HEAL                         ; 0d
	const MUSIC_ROUTE_2                      ; 0f
	const MUSIC_MT_MOON                      ; 10
	const MUSIC_SHOW_ME_AROUND               ; 11
	const MUSIC_GAME_CORNER                  ; 12
	const MUSIC_BICYCLE                      ; 13
	const MUSIC_HALL_OF_FAME                 ; 14
	const MUSIC_VIRIDIAN_CITY                ; 15
	const MUSIC_CELADON_CITY                 ; 16
	const MUSIC_TRAINER_VICTORY              ; 17
	const MUSIC_WILD_VICTORY                 ; 18
	const MUSIC_GYM_VICTORY                  ; 19
	const MUSIC_GYM                          ; 1b
	const MUSIC_PALLET_TOWN                  ; 1c
	const MUSIC_POKEMON_TALK                 ; 1d
	const MUSIC_PROF_OAK                     ; 1e
	const MUSIC_RIVAL_ENCOUNTER              ; 1f
	const MUSIC_SURF                         ; 20
	const MUSIC_EVOLUTION                    ; 21
	const MUSIC_ROUTE_206                    ; 22
	const MUSIC_CREDITS                      ; 23
	const MUSIC_OREBURGH_CITY                ; 24
	const MUSIC_SANDGEM_TOWN                 ; 25
	const MUSIC_KIMONO_ENCOUNTER             ; 26
	const MUSIC_UNION_CAVE                   ; 27
	const MUSIC_SINNOH_WILD_BATTLE           ; 28
	const MUSIC_SINNOH_TRAINER_BATTLE        ; 29
	const MUSIC_ROUTE_203                    ; 2a
	const MUSIC_ECRUTEAK_CITY                ; 2b
	const MUSIC_VIOLET_CITY                  ; 2c
	const MUSIC_JOHTO_GYM_LEADER_BATTLE      ; 2d
	const MUSIC_CHAMPION_BATTLE              ; 2e
	const MUSIC_RIVAL_BATTLE                 ; 2f
	const MUSIC_ROCKET_BATTLE                ; 30
	const MUSIC_PROF_ROWAN                   ; 31
	const MUSIC_DARK_CAVE                    ; 32
	const MUSIC_ROUTE_205                    ; 33
	const MUSIC_ROUTE_36                     ; 34
	const MUSIC_YOUNGSTER_ENCOUNTER          ; 35
	const MUSIC_BEAUTY_ENCOUNTER             ; 37
	const MUSIC_ROCKET_ENCOUNTER             ; 38
	const MUSIC_POKEMANIAC_ENCOUNTER         ; 39
	const MUSIC_SAGE_ENCOUNTER               ; 3a
	const MUSIC_GOLDENROD_CITY               ; 3b
	const MUSIC_VERMILION_CITY               ; 3d
	const MUSIC_POKEMON_CHANNEL              ; 3e
	const MUSIC_POKE_FLUTE_CHANNEL           ; 3f
	const MUSIC_DAWNS_THEME                  ; 40
	const MUSIC_LUCASS_THEME                 ; 41
	const MUSIC_INDIGO_PLATEAU               ; 45
	const MUSIC_ROUTE_37                     ; 46
	const MUSIC_ROCKET_HIDEOUT               ; 47
	const MUSIC_ETERNA_FOREST                ; 48
	const MUSIC_SINNOH_WILD_BATTLE_NIGHT     ; 49
	const MUSIC_RUINS_OF_ALPH_RADIO          ; 4a
	const MUSIC_CAPTURE                      ; 4b
	const MUSIC_ROUTE_26                     ; 4c
	const MUSIC_MOM                          ; 4d
	const MUSIC_VICTORY_ROAD                 ; 4e
	const MUSIC_POKEMON_LULLABY              ; 4f
	const MUSIC_POKEMON_MARCH                ; 50
	const MUSIC_MAIN_MENU                    ; 51
	const MUSIC_OREBURGH_GATE                ; 54
	const MUSIC_ROCKET_OVERTURE              ; 55
	const MUSIC_BUG_CATCHING_CONTEST_RANKING ; 56
	const MUSIC_BUG_CATCHING_CONTEST         ; 58
	const MUSIC_LAKE_OF_RAGE_ROCKET_RADIO    ; 59
	const MUSIC_PRINTER                      ; 5a
	const MUSIC_POST_CREDITS                 ; 5b
; new to Crystal
	const MUSIC_MOBILE_ADAPTER_MENU          ; 5c
	const MUSIC_MOBILE_ADAPTER               ; 5d
	const MUSIC_BUENAS_PASSWORD              ; 5e
	const MUSIC_MYSTICALMAN_ENCOUNTER        ; 5f
	const MUSIC_CRYSTAL_OPENING              ; 60
	const MUSIC_BATTLE_TOWER_THEME           ; 61
	const MUSIC_SUICUNE_BATTLE               ; 62
	const MUSIC_BATTLE_TOWER_LOBBY           ; 63
	const MUSIC_MOBILE_CENTER                ; 64
; new toPPG2
	const MUSIC_TWINLEAF_TOWN                ; 65
	const MUSIC_ROUTE_201                    ; 66
	const MUSIC_POKE_MART                    ; 67
	const MUSIC_ROUTE_209                    ; 68
	const MUSIC_LOOK_HANDSOME                ; 69
DEF NUM_MUSIC_SONGS EQU const_value

; GetMapMusic picks music for these values (see home/map.asm)
DEF MUSIC_MAHOGANY_MART EQU $fc
DEF MUSIC_RADIO_TOWER   EQU $fd

; ExitPokegearRadio_HandleMusic uses these values
DEF RESTART_MAP_MUSIC EQU $fe
DEF ENTER_MAP_MUSIC   EQU $ff
