Debug_MusicNames::
	db "None@@@@@@@@@@@@@@"
	db "Crystal Title@@@@@"
	db "Route 1@@@@@@@@@@@"
	db "Route 3@@@@@@@@@@@"
	db "Route 12@@@@@@@@@@"
	db "Special Program@@@"
	db "Pokemon Center@@@@"
	db "Hiker Encounter@@@"
	db "Lass Encounter@@@@"
	db "Officer Encounter@"
	db "Pokemon Healed@@@@"
	db "Route 2@@@@@@@@@@@"
	db "Mt. Moon@@@@@@@@@@"
	db "Show Me Around@@@@"
	db "Game Corner@@@@@@@"
	db "Bicycle@@@@@@@@@@@"
	db "Hall of Fame@@@@@@"
	db "Viridian City@@@@@"
	db "Celadon City@@@@@@"
	db "Trainer Victory@@@"
	db "Wild Victory@@@@@@"
	db "Gym Victory@@@@@@@"
	db "Gym@@@@@@@@@@@@@@@"
	db "Pallet Town@@@@@@@"
	db "Pokemon Talk@@@@@@"
	db "Prof. Oak@@@@@@@@@"
	db "Rival Encounter@@@"
	db "Surf@@@@@@@@@@@@@@"
	db "Evolution@@@@@@@@@"
	db "Route 206@@@@@@@@@"
	db "Credits@@@@@@@@@@@"
	db "Oreburgh City@@@@@"
	db "Sandgem Town@@@@@@"
	db "Kimono Encounter@@"
	db "Union Cave@@@@@@@@"
	db "Sinnoh Wild Enc.@@"
	db "Johto Trainer@@@@@"
	db "Route 203@@@@@@@@@"
	db "Ecruteak City@@@@@"
	db "Violet City@@@@@@@"
	db "Johto Gym Battle@@"
	db "Champion Battle@@@"
	db "Rival Battle@@@@@@"
	db "Rocket Battle@@@@@"
	db "Prof. Rowan@@@@@@@"
	db "Dark Cave@@@@@@@@@"
	db "Route 205@@@@@@@@@"
	db "Route 36@@@@@@@@@@"
	db "Youngster Enc.@@@@"
	db "Beauty Encounter@@"
	db "Rocket Encounter@@"
	db "Pokemaniac Enc.@@@"
	db "Sage Encounter@@@@"
	db "Goldenrod City@@@@"
	db "Vermilion City@@@@"
	db "Pokemon Channel@@@"
	db "PokeFlute Channel@"
	db "Dawn's Theme@@@@@@@"
	db "Lucas's Theme@@@@@@"
	db "Indigo Plateau@@@@"
	db "Route 37@@@@@@@@@@"
	db "Rocket Hideout@@@@"
	db "Eterna Forest@@@@@"
	db "Sinnoh Wild Night@"
	db "RuinsAlph Radio@@@"
	db "Capture@@@@@@@@@@@"
	db "Route 26@@@@@@@@@@"
	db "Mom@@@@@@@@@@@@@@@"
	db "Victory Road@@@@@@"
	db "Pokemon Lullaby@@@"
	db "Pokemon March@@@@@"
	db "Main Menu@@@@@@@@@"
	db "Oreburgh Gate@@@@@"
	db "Rocket Overture@@@"
	db "Bug Contest Rslt@@"
	db "Bug Contest@@@@@@@"
	db "Evolution Radio@@@"
	db "Printer@@@@@@@@@@@"
	db "The End@@@@@@@@@@@"
	db "Mobile Menu@@@@@@@"
	db "Mobile Adapter@@@@"
	db "Buena's Password@@@"
	db "Eusine Encounter@@"
	db "Crystal Opening@@@"
	db "Battle Tower@@@@@@"
	db "Suicine Battle@@@@"
	db "B.Tower Lobby@@@@@"
	db "Mobile Center@@@@@"
	db "Twinleaf Town@@@@@"
	db "Route 201@@@@@@@@@"
	db "PokeMart@@@@@@@@@@"
