; See song sections in audio.asm.

Music:
; entries correspond to MUSIC_* constants
	table_width 3, Music
	dba Music_Nothing
	dba Music_TitleScreen
	dba Music_Route1
	dba Music_Route3
	dba Music_Route12
	dba Music_SpecialProgram
	dba Music_PokemonCenter
	dba Music_LookHiker
	dba Music_LookLass
	dba Music_LookOfficer
	dba Music_HealPokemon
	dba Music_Route2
	dba Music_MtMoon
	dba Music_ShowMeAround
	dba Music_GameCorner
	dba Music_Bicycle
	dba Music_HallOfFame
	dba Music_ViridianCity
	dba Music_CeladonCity
	dba Music_TrainerVictory
	dba Music_WildPokemonVictory
	dba Music_GymLeaderVictory
	dba Music_Gym
	dba Music_PalletTown
	dba Music_ProfOaksPokemonTalk
	dba Music_ProfOak
	dba Music_LookRival
	dba Music_Surf
	dba Music_Evolution
	dba Music_Route206
	dba Music_Credits
	dba Music_OreburghCity
	dba Music_SandgemTown
	dba Music_LookKimonoGirl
	dba Music_UnionCave
	dba Music_SinnohWildBattle
	dba Music_SinnohTrainerBattle
	dba Music_Route203
	dba Music_EcruteakCity
	dba Music_VioletCity
	dba Music_SinnohGymBattle
	dba Music_ChampionBattle
	dba Music_RivalBattle
	dba Music_RocketBattle
	dba Music_RowansLab
	dba Music_DarkCave
	dba Music_Route205
	dba Music_Route36
	dba Music_LookYoungster
	dba Music_LookBeauty
	dba Music_LookRocket
	dba Music_LookPokemaniac
	dba Music_LookSage
	dba Music_GoldenrodCity
	dba Music_VermilionCity
	dba Music_PokemonChannel
	dba Music_PokeFluteChannel
	dba Music_DawnsTheme
	dba Music_LucassTheme
	dba Music_IndigoPlateau
	dba Music_Route37
	dba Music_RocketHideout
	dba Music_EternaForest
	dba Music_SinnohWildBattleNight
	dba Music_RuinsOfAlphRadio
	dba Music_SuccessfulCapture
	dba Music_Route26
	dba Music_Mom
	dba Music_VictoryRoad
	dba Music_PokemonLullaby
	dba Music_PokemonMarch
	dba Music_MainMenu
	dba Music_OreburghGate
	dba Music_RocketTheme
	dba Music_ContestResults
	dba Music_BugCatchingContest
	dba Music_LakeOfRageRocketRadio
	dba Music_Printer
	dba Music_PostCredits
; new to Crystal
	dba Music_MobileAdapterMenu
	dba Music_MobileAdapter
	dba Music_BuenasPassword
	dba Music_LookMysticalMan
	dba Music_CrystalOpening
	dba Music_BattleTowerTheme
	dba Music_SuicuneBattle
	dba Music_BattleTowerLobby
	dba Music_MobileCenter
; new to PPG2
	dba Music_TwinleafTown
	dba Music_Route201
	dba Music_PokeMart
	dba Music_Route209
	dba Music_LookHandsome
	assert_table_length NUM_MUSIC_SONGS
